### ISSUE TITLE
Отдельный репозиторий с конфигурацией ESLint

### ISSUE THREAD

**Issue by ExEr7um** [Pacific-Agency/eslint-config#1]
Конфигурацию можно вынести в отдельный репозиторий, после чего использовать в проектах через `extends`. Этот проект нужно выложить на GitHub Packages, после чего добавить в репозитории фронтенда.

```[tasklist]
### Конфигурация
- [ ] https://github.com/Pacific-Agency/eslint-config/issues/2
- [ ] https://github.com/Pacific-Agency/eslint-config/issues/3
```

```[tasklist]
### Tasks
- [ ] https://github.com/Pacific-Agency/eslint-config/issues/4
- [ ] https://github.com/Pacific-Agency/eslint-config/issues/5
- [ ] https://github.com/Pacific-Agency/eslint-config/issues/6
- [ ] https://github.com/Pacific-Agency/eslint-config/issues/7
```

## Ссылки
- [Документация ESLint](https://eslint.org/docs/latest/extend/shareable-configs)
- [Пример репозитория для Prettier](https://github.com/Pacific-Agency/prettier-config)
